name: PHPUnit

on: [push,workflow_dispatch]

jobs:
  phpunit:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
 
    - name: Install composer dependencies
      run: |
        composer install --no-scripts
        php artisan jwt:secret
 
    - name: RUNNING ALL UNIT TESTS
      run: vendor/bin/phpunit tests/